import PDFDocument from "pdfkit";

export function generateInvoicePdf(invoice, po, vendor, items) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks = [];
    doc.on("data", (c) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(22).fillColor("#0d9488").text("VendorBridge", { align: "left" });
    doc.fontSize(10).fillColor("#666").text("Procurement & Vendor Management ERP");
    doc.moveDown();

    doc.fontSize(18).fillColor("#111").text("TAX INVOICE", { align: "right" });
    doc.fontSize(10).fillColor("#333");
    doc.text(`Invoice #: ${invoice.invoice_number}`, { align: "right" });
    doc.text(`PO #: ${po.po_number}`, { align: "right" });
    doc.text(`Date: ${new Date(invoice.created_at).toLocaleDateString()}`, { align: "right" });
    doc.moveDown();

    doc.fontSize(12).fillColor("#111").text("Bill To:");
    doc.fontSize(10).fillColor("#333");
    doc.text("VendorBridge Organization");
    doc.text("Procurement Department");
    doc.moveDown();

    doc.fontSize(12).fillColor("#111").text("Vendor:");
    doc.fontSize(10).fillColor("#333");
    doc.text(vendor.name);
    if (vendor.gst_number) doc.text(`GST: ${vendor.gst_number}`);
    doc.text(vendor.email);
    if (vendor.address) doc.text(vendor.address);
    doc.moveDown();

    const tableTop = doc.y + 10;
    const col = { item: 50, qty: 280, price: 350, total: 450 };
    doc.fontSize(10).fillColor("#fff");
    doc.rect(50, tableTop, 500, 22).fill("#0d9488");
    doc.fillColor("#fff").text("Item", col.item + 5, tableTop + 6);
    doc.text("Qty", col.qty, tableTop + 6);
    doc.text("Unit Price", col.price, tableTop + 6);
    doc.text("Total", col.total, tableTop + 6);

    let y = tableTop + 30;
    doc.fillColor("#333");
    for (const item of items) {
      doc.text(item.product_name, col.item, y, { width: 220 });
      doc.text(String(item.quantity), col.qty, y);
      doc.text(`₹${Number(item.unit_price).toFixed(2)}`, col.price, y);
      doc.text(`₹${Number(item.total_price).toFixed(2)}`, col.total, y);
      y += 22;
    }

    y += 10;
    doc.moveTo(350, y).lineTo(550, y).stroke("#ddd");
    y += 12;
    doc.text("Subtotal:", 350, y);
    doc.text(`₹${Number(invoice.subtotal).toFixed(2)}`, col.total, y);
    y += 18;
    doc.text("Tax:", 350, y);
    doc.text(`₹${Number(invoice.tax_amount).toFixed(2)}`, col.total, y);
    y += 18;
    doc.fontSize(12).fillColor("#111").text("Total:", 350, y);
    doc.text(`₹${Number(invoice.total_amount).toFixed(2)}`, col.total, y);

    doc.fontSize(9).fillColor("#999").text(
      "Generated by VendorBridge ERP — This is a computer-generated document.",
      50,
      doc.page.height - 50,
      { align: "center", width: 500 },
    );

    doc.end();
  });
}
